// EscrowX Solana Audit Client Example
// This demonstrates how to interact with the audit program from a Node.js/TypeScript application

import {
  Connection,
  PublicKey,
  clusterApiUrl,
  Keypair,
  SystemProgram,
  Transaction,
} from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import fs from "fs";

// Program ID - update this with your deployed program ID
const PROGRAM_ID = new PublicKey("6v2iemgJm3wqRmL36frHKAMNRMwjg5NdgjTjmtfamfvj");

// IDL for the program - this would normally be generated by Anchor
const IDL = {
  version: "0.1.0",
  name: "escrowx_audit",
  instructions: [
    {
      name: "writeLifecycleRecord",
      accounts: [
        { name: "escrowRecord", isMut: true, isSigner: true },
        { name: "signer", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "listingId", type: "u64" },
        { name: "ethTxHash", type: "string" },
        { name: "actor", type: "publicKey" },
        { name: "amount", type: "u64" },
      ],
    },
    {
      name: "writeDisputeRecord",
      accounts: [
        { name: "escrowRecord", isMut: true, isSigner: true },
        { name: "signer", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "listingId", type: "u64" },
        { name: "ethTxHash", type: "string" },
        { name: "actor", type: "publicKey" },
        { name: "proofHash", type: "string" },
      ],
    },
  ],
  accounts: [
    {
      name: "EscrowRecord",
      type: {
        kind: "struct",
        fields: [
          { name: "listingId", type: "u64" },
          { name: "recordType", type: "u8" },
          { name: "ethTxHash", type: "string" },
          { name: "actor", type: "publicKey" },
          { name: "amount", type: "u64" },
          { name: "proofHash", type: { option: "string" } },
          { name: "timestamp", type: "i64" },
        ],
      },
    },
  ],
};

export class EscrowXAuditClient {
  private connection: Connection;
  private program: anchor.Program;
  private wallet: anchor.Wallet;

  constructor(keypairPath: string, cluster: string = "devnet") {
    // Setup connection
    const clusterUrl = cluster === "devnet" ? clusterApiUrl("devnet") : clusterApiUrl("mainnet-beta");
    this.connection = new Connection(clusterUrl, "confirmed");

    // Load wallet
    const keypairFile = fs.readFileSync(keypairPath);
    const keypair = Keypair.fromSecretKey(new Uint8Array(JSON.parse(keypairFile.toString())));
    this.wallet = new anchor.Wallet(keypair);

    // Setup provider and program
    const provider = new anchor.AnchorProvider(this.connection, this.wallet, {});
    this.program = new anchor.Program(IDL as any, PROGRAM_ID, provider);
  }

  /**
   * Write a lifecycle record to the audit ledger
   */
  async writeLifecycleRecord(
    listingId: number,
    ethTxHash: string,
    actor: PublicKey,
    amount: number
  ): Promise<{ signature: string; accountPubkey: PublicKey }> {
    const escrowAccount = Keypair.generate();

    try {
      const signature = await this.program.methods
        .writeLifecycleRecord(
          new anchor.BN(listingId),
          ethTxHash,
          actor,
          new anchor.BN(amount)
        )
        .accounts({
          escrowRecord: escrowAccount.publicKey,
          signer: this.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([escrowAccount])
        .rpc();

      console.log(`✅ Lifecycle record created: ${signature}`);
      return { signature, accountPubkey: escrowAccount.publicKey };
    } catch (error) {
      console.error("❌ Error creating lifecycle record:", error);
      throw error;
    }
  }

  /**
   * Write a dispute record to the audit ledger
   */
  async writeDisputeRecord(
    listingId: number,
    ethTxHash: string,
    actor: PublicKey,
    proofHash: string
  ): Promise<{ signature: string; accountPubkey: PublicKey }> {
    const escrowAccount = Keypair.generate();

    try {
      const signature = await this.program.methods
        .writeDisputeRecord(
          new anchor.BN(listingId),
          ethTxHash,
          actor,
          proofHash
        )
        .accounts({
          escrowRecord: escrowAccount.publicKey,
          signer: this.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([escrowAccount])
        .rpc();

      console.log(`✅ Dispute record created: ${signature}`);
      return { signature, accountPubkey: escrowAccount.publicKey };
    } catch (error) {
      console.error("❌ Error creating dispute record:", error);
      throw error;
    }
  }

  /**
   * Fetch an escrow record by account address
   */
  async fetchRecord(accountPubkey: PublicKey): Promise<any> {
    try {
      const record = await this.program.account.escrowRecord.fetch(accountPubkey);
      return {
        listingId: record.listingId.toNumber(),
        recordType: record.recordType,
        ethTxHash: record.ethTxHash,
        actor: record.actor.toString(),
        amount: record.amount.toNumber(),
        proofHash: record.proofHash,
        timestamp: new Date(record.timestamp.toNumber() * 1000),
      };
    } catch (error) {
      console.error("❌ Error fetching record:", error);
      throw error;
    }
  }

  /**
   * Get all records for a specific listing ID
   */
  async getRecordsForListing(listingId: number): Promise<any[]> {
    try {
      const accounts = await this.program.account.escrowRecord.all();
      return accounts
        .filter((account) => account.account.listingId.toNumber() === listingId)
        .map((account) => ({
          address: account.publicKey.toString(),
          listingId: account.account.listingId.toNumber(),
          recordType: account.account.recordType,
          ethTxHash: account.account.ethTxHash,
          actor: account.account.actor.toString(),
          amount: account.account.amount.toNumber(),
          proofHash: account.account.proofHash,
          timestamp: new Date(account.account.timestamp.toNumber() * 1000),
        }));
    } catch (error) {
      console.error("❌ Error fetching records for listing:", error);
      throw error;
    }
  }
}

// Example usage
async function example() {
  // Initialize client (you need to provide your keypair path)
  const client = new EscrowXAuditClient("~/.config/solana/id.json", "devnet");

  try {
    // Example 1: Write a lifecycle record
    const lifecycleResult = await client.writeLifecycleRecord(
      1, // listing_id
      "0x1234567890abcdef1234567890abcdef12345678", // eth_tx_hash
      client.wallet.publicKey, // actor
      1000000 // amount in wei
    );

    console.log("Lifecycle record created:", lifecycleResult);

    // Example 2: Write a dispute record
    const disputeResult = await client.writeDisputeRecord(
      1, // listing_id
      "0xabcdef1234567890abcdef1234567890abcdef12", // eth_tx_hash
      client.wallet.publicKey, // actor
      "QmYjtig7VJQ6XsnUjqqJvj7QaMcCAwtrgNdahSiFofrE7o" // proof_hash
    );

    console.log("Dispute record created:", disputeResult);

    // Example 3: Fetch the records
    const lifecycleRecord = await client.fetchRecord(lifecycleResult.accountPubkey);
    const disputeRecord = await client.fetchRecord(disputeResult.accountPubkey);

    console.log("Lifecycle record data:", lifecycleRecord);
    console.log("Dispute record data:", disputeRecord);

    // Example 4: Get all records for listing ID 1
    const allRecords = await client.getRecordsForListing(1);
    console.log("All records for listing 1:", allRecords);
  } catch (error) {
    console.error("Example failed:", error);
  }
}

// Uncomment to run the example
// example();